---
title: "Self Introductions"
format: html
---

Enter your self-introduction here:

Hi everyone!

I'm May Liu, a research intern at IMBHR. I graduated from UNC Chapel Hill in 2024 with dual degrees in psychology and computer science. I'm interested in psychometrics, statistical modeling, and data science. In the future, I plan to apply for PhD programs in quantitative psychology. In my free time, I enjoy reading, playing Nintendo Switch, and watching movies.

Hello, I am Guillermo. I am creating a new branch called GPA.

Hi, I'm Marissa. I'm a clinical research coordinator in IMBHR. I graduated from UNC Charlotte in 2024 with a B.S. in psychology. I enjoy going on evening walks, watch psychological thrillers, and finding new coffee shops.

Hi, I'm Ally, I just graduated from Iowa State University with BS degrees in psych and statistics. I'm excited to start my Ph.D. in clinical psychology this fall at OSU. In my free time, I like to read, hang with my dog Milo, and go for walks.

Hi! I'm Cameron, and I'm a research intern at IMBHR. I graduated from UNC-CH in 2025 in psychology, and I'm super interested in both counseling psychology and science communication. I love trying new crafts, trying to take my cat on walks, and watching documentaries!

Hi, I'm Rylee. I just finished my second year in the Intellectual and Developmental Disabilities Psychology PhD program at OSU. I love to be outside on a sunny day and I have a mini schnauzer named Ozzy!

Hi I'm Sammy. I just finished my third year as an undergrad at Ohio State as a neuroscience major.

